### ISSUE TITLE
Redirect visitors from hsdecktracker.net to hsreplay.net/downloads

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsdecktracker.net#8]
As a user interested in a deck tracker for Hearthstone, I want to be find a compelling page to download a deck tracker for my platform.

As we're currently competing with ourselves between hsdecktracker.net and hsreplay.net, we want to strengthen the newly redesigned downloads page on https://hsreplay.net/downloads/ which does a better job at explaining the deck tracker's features and strengthens the brand association between HSReplay.net and Hearthstone Deck Tracker. We should therefore redirect the traffic hitting hsdecktracker.net to hsreplay.net.
We can leave the existing download "detail" pages on hsdecktracker.net where they are to preserve bookmarks/search machine indexes for the time being.

This story is complete, once:
- [x] We have updated the hsdecktracker.net home page to issue a permanent redirect to https://hsreplay.net/downloads/
- [x] We have requested that hsdecktracker.net is reindexed using the Google Search Console

**Comment by judge2020** [comment]
Would like to note that, for the video on the new download page, I believe it would be better if the video element was tagged `autoplay loop muted`. Since it has no sound Chrome will have no problem autoplaying it and would likely increase the conversion rate.

**Comment by beheh** [comment]
@judge2020 I think we specifically deferred loading in order to make the site not look busy, and probably also to prevent mobile visitors from immediately downloading the video. We might do this in future though!

Otherwise this can be closed, the redirect was done.
